### ISSUE TITLE
Filter to lines NOT containing

### ISSUE THREAD

**Issue by TorKlingberg** [davidpeckham/sublime-filterlines#35]
I would like to filter to only lines that do not contain a certain string or match a certain regex. Like grep -v.

**Comment by TorKlingberg** [comment]
I now found that there is a preference "invert_search": true that does this, but that is a permanent setting. I would like to change it on a case by case basis.

**Comment by airdrummingfool** [comment]
Similarly, it would be nice to have an easy way to toggle the invert_search option rather than editing the user preference. Perhaps a checkbox in the menu? Or just two more menu items that say "Filter (Invert) with [Regex/String]".

Thanks for this great plugin!

**Comment by ndewhurst** [comment]
For now, we can achieve this by building the negation into our regexes using negative "lookaround" assertions. E.g. to display only lines that *do not* contain the string "foobar," start a *Filter Lines: Filter by Regex* operation and use `^((?!foobar).)*$` as the regex.
Obviously it's a bit cumbersome, and I'm assuming it's less efficient than inverting the action in the plugin itself, but at least it's an option.

**Comment by joejcon1** [comment]
+1 on this feature request. (Thanks for explaining how to put the negation into the query though, very useful)

**Comment by Summer006** [comment]
+1 !

**Comment by poma** [comment]
I implemented it [here](https://github.com/poma/sublime-filterlines/commits/master). If someone tests it I can make a pull request.
