### ISSUE TITLE
Allow option for returning leading/trailing lines around matches for context

### ISSUE THREAD

**Issue by joejcon1** [davidpeckham/sublime-filterlines#36]
I often want to search for a regex match with some context, like grep's -A and -B options.

For example:

file:

```
line 1
line 2 
foo
bar
line 5
line 6
```

Searching for "foo -A1 -B2" returns:

```
line 2
foo
bar
line 5
```

**Comment by quique0194** [comment]
:+1:

**Comment by Puccet** [comment]
Me too!

**Comment by davidpeckham** [comment]
I like this idea, and think it would make for a useful plugin, but it's beyond the scope of this plugin.
