### ISSUE TITLE
Feature Request: Allow for Custom Filter/Folding Expressions

### ISSUE THREAD

**Issue by awagner-mainz** [davidpeckham/sublime-filterlines#43]
Hi,
first of all thank you for your plugin which I find very useful. I am very frequently using a certain regular filter expression, and want to create a (keyboard or menu) shortcut which calls the folding command with this expression predefined. It would be great if the command would accept some such string as one if its parameters.
I am totally unexperienced in python, so I will not be able to try this myself very soon...

**Comment by poma** [comment]
You can already do that, use `view.run_command('fold_to_lines', {'needle': 'search word', 'search_type': 'regex'})`

**Comment by davidpeckham** [comment]
Thank you Poma.
