### ISSUE TITLE
it is not clear how to install it

### ISSUE THREAD

**Issue by uglycoyote** [davidpeckham/sublime-filterlines#44]
You don't give any instructions on how to install this plugin.

Searching the internet for "how to install a sublime package" mostly explains how to use package manager, which is already extremely obvious but does not help me.

Searching the internet for "how to install a sublime package without package manager" leads me to a rabbit hole of forums which don't immediately provide any illuminating answers about what to do with your files from github.

thanks.

**Comment by poma** [comment]
If you have package manager: ctrl-shift-p (command palette) -> Install package -> Filter Lines -> done.

If you don't have package manager: clone this repo and place it into Packages folder (Preferences -> Browse packages...). Done.

**Comment by uglycoyote** [comment]
Thanks.  It does appear in package manager.  I'm pretty sure I tried package manager at the time when I posted this issue and did not find the package, hence my comment that "package manager is obvious but does not help me".  Anyhow, I have installed it successfully using package manager, thanks!
