### ISSUE TITLE
'Filter Results' tab is always empty

### ISSUE THREAD

**Issue by Gabriel-p** [davidpeckham/sublime-filterlines#46]
I've tried this extension on several types of files, specifically the option `Filter lines: Include lines with Strings` and it always opens an empty *Filter Results* tab.

Sublime Text 3 Build 3126, elementary OS (based on ubuntu 16.04, 64 bit)

**Comment by am6422** [comment]
Same for me Ubuntu 16.04 Build 3126..Missing occur emacs....:(

**Comment by davidpeckham** [comment]
Are you still experiencing this?

**Comment by Gabriel-p** [comment]
Nope, seems to work now.
