### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by sketch34** [davidpeckham/sublime-filterlines#47]
Thanks for the awesome plugin!

But I just thought I'd suggest that you add install instructions. You're plugin is the #1 google hit for "sublime text filter" but I had to go find another one that had install instructions. I'm a dev but not a Sublime text pro, and in general I'm too busy to spend more than a couple of mins on stuff like this.

But not too busy to give you a tip to help your repo get more installs! ;) Because these contribs are so valuable. Thanks again, just a suggestion.

**Comment by Gosasan** [comment]
Hi,
I agree. This is one of the top results in google but I can't figure out how to install this. Could you please add the steps? Thanks!!!
