### ISSUE TITLE
Matching over several lines

### ISSUE THREAD

**Issue by levelont** [davidpeckham/sublime-filterlines#51]
I want to match

    "documentType": {
        "id": 72
    }

and started playing with `'"documentType": {\n'` as a regex. That, however, returns an empty list of results.

**Note**: the built-in regex search of sublime text matches the above string with the regex `'"documentType": {\n.*\n\s+}'`

How to go about matching multiple lines in a document?

Thanks in advance!

**Comment by davidpeckham** [comment]
That sounds like an interesting feature, but it's beyond the scope of Filter Lines.
